### PR TITLE
Functions to parse gadget formulae to/from native R expressions

### PR DESCRIPTION
**Pull request by lentinj**
Instead of parsing and evaluating in one go like `eval.gadget.formula` does, these routines convert to/from R expressions. This means that you can do the following:

```
> exp <- parse.gadget.formulae("( * #Linf (-  1 (exp (* (* -1 ( * 0.001 #k) ) (- 1 (+ 1 (/ (log (- 1 (/ #recl #Linf))) ( * 0.001 #k))))))))")
> str(exp)
 language Linf * (1 - exp(-1 * (0.001 * k) * (1 - (1 + log(1 - recl/Linf)/(0.001 * k)))))
> eval(exp, list(Linf = 40, k = 899, recl = 3))
[1] 3
```

..and we can go backwards:

```
> to.gadget.formulae(quote(Linf * (1 - exp(-1 * (0.001 * k) * (1 - (1 + log(1 - recl/Linf)/(0.001 * k)))))))
[1] "(* #Linf (( (- 1 (exp (* (* (- 1) (( (* 0.001 #k))) (( (- 1 (( (+ 1 (/ (log (- 1 (/ #recl #Linf))) (( (* 0.001 #k))))))))))))"
```

One major difference here is that `eval.gadget.formula` uses `prod` and `sum` in R, not `*` and `+`. The difference is the former take any number of arguments, the latter only take 2. The documentation doesn't say if `(+ 2 2 2)` is a valid GADGET formulae, but it seems unlikely it would be.

It should be pretty obvious how to gut `eval.gadget.formula` and replace with the above, which can do if it seems fine. `merge.formula` I don't quite understand.

The other next step is to modify the table component parsing to split up rows according to formulae before `read.table` parses it. Then we can use `colClasses` to read rows as formulae.

### CODE REVIEW

**Comment by bthe** [comment]
I think the parser in Gadget allows `(+ 2 2 2 2)`, and confusingly `(- 2 2 2)` but since this is hardly ever used I guess this is a fair assumption. To avoid confusion the parser in Gadget can be changed;)

 `merge.formula` is a worker function for gadget.table which used to read columns from formula tables, such as renewal and initial value tables, as regular `read.table` chokes on that.

**Comment by lentinj** [comment]
> merge.formula is a worker function for gadget.table which used to read columns from formula tables, such as renewal and initial value tables, as regular read.table chokes on that.

Aha, yes that makes sense. However `read.table` should be okay if you tell it `sep = "\t"` (as opposed to separating on any whitespace) and rows are of the form:

```
col1[-tab-](formula (in col 2))[-tab-](formula (in col 3))
```

Looking through the gadget files I've got, most of the files are like that. I'm guessing you're going to say there's exceptions to that rule though :)

**Comment by bthe** [comment]
> Looking through the gadget files I've got, most of the files are like that. I'm guessing you're going to say there's exceptions to that rule though :)

Sadly yes;) These files are often hand edited and gadget looks only for white-space. Another place where I have used `merge.fomula` is when I was trying to read and parse formulas from the model files (such as suitabilty parameters).

**Comment by lentinj** [comment]
Okay, not the end of the world. We have to buffer the input before handing to `read.table` anyway so there's scope for cleanup.

**Pull request merged**
